export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

NETLIGHT_CODEPILOT_API_KEY="sk-UMfomVnHUN4tyE2rbIWCww"
NETLIGHT_CODEPILOT_BASE_URL="https://llm-proxy.edgez.live/"

export NETLIGHT_CODEPILOT_API_KEY="${NETLIGHT_CODEPILOT_API_KEY}"
export ANTHROPIC_AUTH_TOKEN="${NETLIGHT_CODEPILOT_API_KEY}"
export ANTHROPIC_BASE_URL="${NETLIGHT_CODEPILOT_BASE_URL}"
export OPENAI_BASE_URL="${NETLIGHT_CODEPILOT_BASE_URL}"
export OPENAI_API_KEY="${NETLIGHT_CODEPILOT_API_KEY}"
